- name: Install-Elasticsearch-Kibana
  hosts: es
  user: root
  roles:
    - tools
    - nginx
    - es
    - td-agent
    - kibana
    - restart
  vars:
    proxy: false
    proxy_host: example.com
    proxy_port: 8080
